name: Pull Request CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Run Lint
      run: yarn run lint
    - name: Run Format Check
      run: yarn run check-formatting
    - name: Run Format Check
      run: yarn run check-types
    - name: Run Unit Test Suite
      run: yarn run test